# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZhiXiangJiaSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZhiXiangJiaSwift

     pod 'SnapKit'
     pod 'SVProgressHUD'
     pod 'Kingfisher'
     pod 'IQKeyboardManagerSwift'
     pod 'Moya'
     pod 'SwiftyJSON'
     pod 'Reachability'
     pod 'Result'
     pod 'MBProgressHUD'
     pod 'MJRefresh'
     pod 'DNSPageView'


end
